# Device identity in AWS IoT Core.
#
# Every machine is a Thing with its own X.509 certificate and its own policy. The policy is
# the security boundary that matters: it names the asset's own topics literally, so a
# compromised machine cannot read another machine's commands, publish telemetry as another
# machine, or subscribe to the fleet wildcard. One machine on a plant floor being physically
# accessible is a normal risk; that machine being able to impersonate the rest of the fleet is
# not.
#
# This is also why the broker is a managed service rather than something hand-rolled: per
# device identity, mutual TLS, and revocation are the parts of a fleet transport most likely
# to be got wrong, and IoT Core owns them.

data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

# The ATS (Amazon Trust Services) data endpoint. Its certificate chains to a root the agent
# can validate with a widely distributed CA bundle, unlike the legacy Symantec endpoint.
data "aws_iot_endpoint" "ats" {
  endpoint_type = "iot:Data-ATS"
}

locals {
  name_prefix = "${var.project}-${var.environment}"
  account_id  = data.aws_caller_identity.current.account_id
  region      = data.aws_region.current.region

  iot_arn_prefix = "arn:aws:iot:${local.region}:${local.account_id}"

  # Each asset's topic prefix, resolved once so the policy, the agent config and the docs
  # cannot drift apart.
  asset_topics = {
    for id, asset in var.assets :
    id => "${var.mqtt_topic_prefix}/${asset.site_id}/${id}"
  }
}

resource "aws_iot_thing_type" "asset" {
  name = "${local.name_prefix}-asset"

  properties {
    description = "A monitored plant-floor machine running the FactoryFleet agent."
    # Searchable attributes make fleet indexing useful later: "every hydraulic press at
    # PLANT-A" becomes a query rather than a scan.
    searchable_attributes = ["siteId", "machineType"]
  }
}

resource "aws_iot_thing" "asset" {
  for_each = var.assets

  name            = each.key
  thing_type_name = aws_iot_thing_type.asset.name

  attributes = {
    siteId      = each.value.site_id
    machineType = each.value.machine_type
  }
}

# One certificate per machine. Per-asset rather than per-fleet so a single machine can be
# revoked — pulled from service, sold, or compromised — without reissuing credentials to
# every other machine.
resource "aws_iot_certificate" "asset" {
  for_each = var.assets

  active = true
}

resource "aws_iot_thing_principal_attachment" "asset" {
  for_each = var.assets

  thing     = aws_iot_thing.asset[each.key].name
  principal = aws_iot_certificate.asset[each.key].arn
}

data "aws_iam_policy_document" "asset" {
  for_each = var.assets

  # The client id is pinned to the asset id, so a stolen certificate cannot be used to
  # connect as a different machine. The agent defaults its client id to the asset id for
  # exactly this reason.
  statement {
    sid       = "ConnectAsThisAssetOnly"
    actions   = ["iot:Connect"]
    resources = ["${local.iot_arn_prefix}:client/${each.key}"]
  }

  statement {
    sid     = "PublishOwnTelemetryAndResults"
    actions = ["iot:Publish"]
    resources = [
      "${local.iot_arn_prefix}:topic/${local.asset_topics[each.key]}/telemetry",
      "${local.iot_arn_prefix}:topic/${local.asset_topics[each.key]}/registration",
      "${local.iot_arn_prefix}:topic/${local.asset_topics[each.key]}/commands/ack",
      "${local.iot_arn_prefix}:topic/${local.asset_topics[each.key]}/commands/result",
    ]
  }

  # Subscribe and Receive are separate actions in IoT Core, and both are needed: Subscribe
  # authorises the request, Receive authorises each delivery. Granting only the first is a
  # common way to end up with a silently empty subscription.
  statement {
    sid       = "SubscribeToOwnCommands"
    actions   = ["iot:Subscribe"]
    resources = ["${local.iot_arn_prefix}:topicfilter/${local.asset_topics[each.key]}/commands"]
  }

  statement {
    sid       = "ReceiveOwnCommands"
    actions   = ["iot:Receive"]
    resources = ["${local.iot_arn_prefix}:topic/${local.asset_topics[each.key]}/commands"]
  }
}

resource "aws_iot_policy" "asset" {
  for_each = var.assets

  name   = "${local.name_prefix}-${each.key}"
  policy = data.aws_iam_policy_document.asset[each.key].json
}

resource "aws_iot_policy_attachment" "asset" {
  for_each = var.assets

  policy = aws_iot_policy.asset[each.key].name
  target = aws_iot_certificate.asset[each.key].arn
}

# Certificate material for the agent to use.
#
# SECURITY: the private key is generated by IoT Core and returned to Terraform, which means it
# is stored in plain text in the Terraform state file. State must therefore be treated as a
# secret — it is git-ignored here, and a remote backend for this project would need encryption
# at rest plus restricted access. The production-grade alternative is for each device to
# generate its own key and submit a CSR (or use fleet provisioning), so the private key never
# leaves the machine and never reaches Terraform at all. That is the right answer for a real
# fleet and overkill for provisioning a handful of demo assets from one laptop.
resource "local_sensitive_file" "asset_private_key" {
  for_each = var.assets

  content         = aws_iot_certificate.asset[each.key].private_key
  filename        = "${var.certificate_output_dir}/${each.key}/private.key"
  file_permission = "0600"
}

resource "local_sensitive_file" "asset_certificate" {
  for_each = var.assets

  content         = aws_iot_certificate.asset[each.key].certificate_pem
  filename        = "${var.certificate_output_dir}/${each.key}/certificate.crt"
  file_permission = "0644"
}
